version: 2.1

orbs:
  docker: circleci/docker@1.2.1

workflows:
  default:
    jobs:
      - docker/hadolint
      - docker/publish:
          image: ssplatt/shellcheck
          update-description: true
          requires:
            - docker/hadolint
          filters:
            branches:
              only:
                - master
